import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import dynamic from "next/dynamic";
import { WidgetProps } from "@worldcoin/id";
import axios from "axios";

const WorldIDWidget = dynamic<WidgetProps>(
  () => import("@worldcoin/id").then((mod) => mod.WorldIDWidget),
  { ssr: false }
);

// --> Cloud Functions
/// verify the Proof by sending a request first and then Moving ahead.
const verifyProof = () => {
  try {
    const config = {
      method: "post",
      url: "https://developer.worldcoin.org/api/v1/verify",
      headers: {
        "Content-Type": "application/json",
      },
      data: {
        merkle_root:
          "0x1f38b57f3bdf96f05ea62fa68814871bf0ca8ce4dbe073d8497d5a6b0a53e5e0",
        nullifier_hash:
          "0x0339861e70a9bdb6b01a88c7534a3332db915d3d06511b79a5724221a6958fbe",
        action_id: "wid_staging_463a9bda2c5c73bf919d94bc59f7e92e",
        signal: "Verify Real users ",
        proof:
          "0x063942fd7ea1616f17787d2e3374c1826ebcd2d41d2394d915098c73482fa59516145cee11d59158b4012a463f487725cb3331bf90a0472e17385832eeaec7a713164055fc43cc0f873d76752de0e35cc653346ec42232649d40f5b8ded28f202793c4e8d096493dc34b02ce4252785df207c2b76673924502ab56b7e844baf621025148173fc74682213753493e8c90e5c224fc43786fcd09b624115bee824618e57bd28caa301f6b21606e7dce789090de053e641bce2ce0999b64cdfdfb0a0734413914c21e4e858bf38085310d47cd4cc6570ed634faa2246728ad64c49f1f720a39530d82e1fae1532bd7ad389978b6f337fcd6fa6381869637596e63a1",
      },
    };
    axios(config)
      .then(function (response) {
        console.log(response);
        // if (response.success) {
        //   /// Move ahead if the Success is true
        // }
      })
      .catch(function (error) {
        console.log(error);
      });
  } catch (error) {
    console.log(error);
  }
};

const widgetProps: WidgetProps = {
  actionId: "wid_staging_463a9bda2c5c73bf919d94bc59f7e92e",
  signal: "Verify Real users ",
  enableTelemetry: true,
  appName: "SwiftFi",
  signalDescription: "Verify that you are a real user to proceed",
  theme: "dark",
  debug: true, // Recommended **only** for development
  onSuccess: (verificationResponse) => console.log(verificationResponse),
  onError: ({ code, detail }) => console.log({ code, detail }),
  onInitSuccess: () => console.log("Init successful"),
  onInitError: (error) =>
    console.log("Error while initialization World ID", error),
};

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>WorldCoin ID Widget Demo App</p>
          <div>
            <WorldIDWidget {...widgetProps} />
          </div>
        </div>

        <div className={styles.center}>By @0xdhruva</div>
      </main>
    </>
  );
}
